trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  version: $[ counter('revision-new',0) ]

steps:
- task: TfxInstaller@1
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: PowerShell@2
  displayName: 'Increment the task version in task.json'
  inputs:
    targetType: 'inline'
    script: |
      $jsonPath = "$(Build.SourcesDirectory)/task/task.json"
      $taskJson = Get-Content $jsonPath | ConvertFrom-Json
      $taskJson.version.Patch = $(Version)
      $taskJson = $taskJson | ConvertTo-Json -Depth 10
      Set-Content -Path $jsonPath -Value $taskJson | ConvertTo-Json



- task: PackageVSTSExtension@1
  displayName: 'Package Extension - Private'
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    extensionVersion: '1.2.$(Version)'
    extensionVisibility: private
    extensionPricing: free
    extensionId: 'CreatePullRequestDev'
    outputPath: '$(Build.ArtifactStagingDirectory)/vsix'

- task: PackageVSTSExtension@1
  displayName: 'Package Extension - Public'
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    extensionVersion: '1.2.$(Version)'
    extensionVisibility: public
    extensionPricing: free
    updateTasksVersion: false
    outputPath: '$(Build.ArtifactStagingDirectory)/vsix'
    
- task: IsAzureDevOpsExtensionValid@2
  displayName: 'Validate VSIX file'
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'AzureDevOps Maketplace'
    method: 'vsix'
    vsixFile: '$(Build.ArtifactStagingDirectory)/vsix/ShaykiAbramczyk.CreatePullRequest*.vsix'
    maxRetries: '1''

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\vsix'